data = [ # made by chatGPT
    {"name": "Cristiano Ronaldo", "from": "Portugal", "follower": 600000000, "job": "Footballer"},
    {"name": "Lionel Messi", "from": "Argentina", "follower": 500000000, "job": "Footballer"},
    {"name": "Kylie Jenner", "from": "USA", "follower": 400000000, "job": "Reality TV Star/Businesswoman"},
    {"name": "Dwayne 'The Rock' Johnson", "from": "USA", "follower": 400000000, "job": "Actor/Wrestler"},
    {"name": "Kim Kardashian", "from": "USA", "follower": 350000000, "job": "Reality TV Star/Businesswoman"},
    {"name": "Ariana Grande", "from": "USA", "follower": 350000000, "job": "Singer/Actress"},
    {"name": "Beyoncé", "from": "USA", "follower": 300000000, "job": "Singer/Actress"},
    {"name": "Selena Gomez", "from": "USA", "follower": 300000000, "job": "Singer/Actress"},
    {"name": "Justin Bieber", "from": "Canada", "follower": 270000000, "job": "Singer"},
    {"name": "Taylor Swift", "from": "USA", "follower": 250000000, "job": "Singer/Songwriter"},
    {"name": "Kendall Jenner", "from": "USA", "follower": 250000000, "job": "Model"},
    {"name": "Shakira", "from": "Colombia", "follower": 250000000, "job": "Singer/Dancer"},
    {"name": "Lebron James", "from": "USA", "follower": 150000000, "job": "Basketball Player"},
    {"name": "Rihanna", "from": "Barbados", "follower": 150000000, "job": "Singer/Businesswoman"},
    {"name": "Demi Lovato", "from": "USA", "follower": 150000000, "job": "Singer/Actress"},
    {"name": "Billie Eilish", "from": "USA", "follower": 150000000, "job": "Singer/Songwriter"},
    {"name": "Zac Efron", "from": "USA", "follower": 120000000, "job": "Actor"},
    {"name": "Emma Watson", "from": "UK", "follower": 120000000, "job": "Actress/Activist"},
    {"name": "Will Smith", "from": "USA", "follower": 100000000, "job": "Actor/Producer"},
    {"name": "Chris Hemsworth", "from": "Australia", "follower": 100000000, "job": "Actor"},
    {"name": "Zendaya", "from": "USA", "follower": 100000000, "job": "Actress/Singer"},
    {"name": "Kourtney Kardashian", "from": "USA", "follower": 100000000, "job": "Reality TV Star"},
    {"name": "Miley Cyrus", "from": "USA", "follower": 100000000, "job": "Singer/Actress"},
    {"name": "Harry Styles", "from": "UK", "follower": 100000000, "job": "Singer/Actor"},
    {"name": "Jennifer Lopez", "from": "USA", "follower": 100000000, "job": "Singer/Actress"},
    {"name": "Khloé Kardashian", "from": "USA", "follower": 100000000, "job": "Reality TV Star"},
    {"name": "Cardi B", "from": "USA", "follower": 100000000, "job": "Rapper/Actress"},
    {"name": "Katy Perry", "from": "USA", "follower": 100000000, "job": "Singer"},
    {"name": "Post Malone", "from": "USA", "follower": 100000000, "job": "Rapper/Singer"},
    {"name": "Shawn Mendes", "from": "Canada", "follower": 100000000, "job": "Singer/Songwriter"},
    {"name": "Neymar Jr.", "from": "Brazil", "follower": 100000000, "job": "Footballer"},
    {"name": "Megan Thee Stallion", "from": "USA", "follower": 100000000, "job": "Rapper"},
    {"name": "Snoop Dogg", "from": "USA", "follower": 100000000, "job": "Rapper/Entrepreneur"},
    {"name": "Oprah Winfrey", "from": "USA", "follower": 100000000, "job": "TV Host/Entrepreneur"},
    {"name": "Tom Holland", "from": "UK", "follower": 100000000, "job": "Actor"},
    {"name": "Ellen DeGeneres", "from": "USA", "follower": 100000000, "job": "TV Host/Comedian"},
    {"name": "Kylie Minogue", "from": "Australia", "follower": 100000000, "job": "Singer/Actress"},
    {"name": "Blake Lively", "from": "USA", "follower": 100000000, "job": "Actress"},
    {"name": "Gigi Hadid", "from": "USA", "follower": 100000000, "job": "Model"},
    {"name": "Priyanka Chopra", "from": "India", "follower": 100000000, "job": "Actress/Producer"},
    {"name": "Virat Kohli", "from": "India", "follower": 100000000, "job": "Cricketer"},
    {"name": "Cristiano Ronaldo Jr.", "from": "Portugal", "follower": 100000000, "job": "Footballer"},
    {"name": "BTS (Bangtan Boys)", "from": "South Korea", "follower": 150000000, "job": "K-Pop Group"},
    {"name": "Blackpink", "from": "South Korea", "follower": 100000000, "job": "K-Pop Group"},
    {"name": "EXO", "from": "South Korea", "follower": 100000000, "job": "K-Pop Group"},
    {"name": "James Charles", "from": "USA", "follower": 100000000, "job": "Makeup Artist/Influencer"},
    {"name": "Charlie D'Amelio", "from": "USA", "follower": 100000000, "job": "TikTok Star"},
    {"name": "Addison Rae", "from": "USA", "follower": 100000000, "job": "TikTok Star/Actress"},
    {"name": "Lizzo", "from": "USA", "follower": 100000000, "job": "Singer/Actress"},
    {"name": "David Beckham", "from": "UK", "follower": 100000000, "job": "Footballer/Entrepreneur"},
    {"name": "Adele", "from": "UK", "follower": 100000000, "job": "Singer"},
    {"name": "Sidharth Malhotra", "from": "India", "follower": 100000000, "job": "Actor"},
    {"name": "Mahesh Babu", "from": "India", "follower": 100000000, "job": "Actor"}
]
